### ISSUE TITLE
getAppleshareRecord using the wrong class (struct) to parse

### ISSUE THREAD

**Issue by ryandeivert** [n0fate/chainbreaker#2]
Lines 551 & 553 of chainbreaker.py (getAppleshareRecord function) utilize the '_INTERNET_PW_HEADER' class for parsing the Apple Share records instead of the appropriate '_APPLE_SHARE_HEADER' class.

I noticed that the the _INTERNET_PW_HEADER class has no field 'Volume' and the  getAppleshareRecord function attempts to use this in 'RecordMeta.Volume', while the _APPLE_SHARE_HEADER class does in fact have that field. I believe it's probably a simple oversight from copy/pasting but could be wrong...

If you'd like, I can make the small changes and perform a pull request to merge them in. Just let me know!

**Comment by n0fate** [comment]
I fixed some code reflecting your message.
I can't have a testing phase for it because I know the Apple Share Record was no more used. ;p

You can check the [r11](https://github.com/n0fate/chainbreaker/commit/e10e4722a1acb11d1db0b71dc99d7d83738c554d)

If you find new issue, please let me know.
Thank you for your bug reporting ;-)

**Comment by ryandeivert** [comment]
I don't have any way to test either, but thank you for the quick fix!
